config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'home#top'
  get "home/about" => "home#about"
  resources :books, only: [:create, :index, :show, :destroy, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates  :title, presence: true
  validates  :body, presence: true, length: { maximum:200 }
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book
  validates :user_id, presence: true, uniqueness: {scope: :book_id}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: {maximum: 50}
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!,except: [:top, :about]

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:name, :introduction, :profile_image_id])
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:success] = "successfully"
      redirect_to book_path(@book)
    else
      @books = Book.all
      @user = current_user
      render "index"
    end
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:success] = "successfully"
      redirect_to book_path(@book)
    else
      render "edit"
    end
  end

  def destroy
    book = Book.find(params[:id])
    if book.user.id == current_user.id
      if book.destroy
        flash[:success] = "successfully"
        redirect_to books_path
      end
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def top

  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    @users = current_user
    if @user == @users

    else
      redirect_to user_path(@users.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "successfully"
      redirect_to user_path(@user.id)
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<h2>New book</h2>
  <%= form_with model: book, local:true do |f| %>
    <div class="from-group">
      <label for="book_title">Title</label>
      <input class="form-control book_title" type="text" name="book[title]" id="book_title">
    </div>
    <div class="from-group">
      <label for="book_opinion">Opinion</label>
      <textarea class="form-control book_body" name="book[body]" id="book_body"></textarea>
    </div>
    <div class="from-group">
      <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
    </div>
  <% end %>

app/views/books/_list.html.erb
  <h2>Books</h2>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th>Title</th>
        <th>Opinion</th>
         <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td>
            <a href="/users/<%= book.user.id %>">
              <%= attachment_image_tag book.user, :profile_image,  size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %>
            </a>
          </td>
          <td><%= link_to book.title, book_path(book) %></td>
          <td><%= book.body %></td>
          <td id="favorites_buttons_<%= book.id %>">
            <%= render 'favorites/favorite', book: book %>
          </td>
          <td>コメント数: <%= book.book_comments.count %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/books/edit.html.erb
<div class="container">
  <h2>Editing Book</h2>

  <%= form_with model: @book, local:true do |f| %>
    <% if @book.errors.any?%>
      <div id="error_explanation">
        <h2><%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Body</h4>
    <%= f.text_area :body %>
    <p><input type="submit" name="commit" value="Update Book" class="btn btn-success" data-disable-with="Update Book" /></p>
  <% end %>
  <%= link_to "Show", book_path %> |
  <%= link_to "Back", books_path %>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2 style="color:red"><%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li style="color:red"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/profile', users: @users %>
      <div class="mt-3">
        <%= render 'books/form', book: @book %>
      </div>
    </div>
    <div class="col-md-8 offset-md-1">
      <%= render 'books/list', users: @users %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
        <table class="table">
          <tr><%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></tr>
          <thead>
            <tr>
              <th>name</th>
              <th><%= @book.user.name %></th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th>introduction</th>
              <th><%= @book.user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <%= link_to edit_user_path(@book.user) do %>
          <i class="btn btn-outline-secondary btn-block fas fa-user-cog"></i>
        <% end %>
      <div class="mt-3">
        <%= render 'books/form', book: @book_new %>
      </div>
    </div>

    <div class='col-md-8 offset-md-1'>
      <h2>Book detail</h2>
      <table class="table table-hover table-inverse">
        <tbody>
          <tr>
            <td>
              <%= attachment_image_tag @book.user, :profile_image,  size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %> </br>
              <%= link_to @book.user.name, "/users/#{@book.user.id}" %>
            </td>
            <td><%= @book.title %></td>
            <td><%= @book.body %></td>
              <td id="favorites_buttons_<%= @book.id %>">
                <%= render 'favorites/favorite', book: @book %>
              </td>
            <% if @book.user.id == current_user.id %>
              <td><%= link_to "Edit", edit_book_path(@book), :class=>"btn btn-sm btn-success edit_book_14426" %></td>
              <td><%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に削除しますか？", :class=> "btn btn-sm btn-danger destroy_book_14426" %></td>
            <% end %>
          </tr>
        </tbody>
      </table>

      <div class="comments">
        <p>コメント件数：<%= @book.book_comments.count %></p>
        <table class="comment-table">
          <tbody>
            <% @book.book_comments.each do |book_comment| %>
            <tr>
              <td><%= book_comment.user.name %></td>
              <td><%= book_comment.comment %></td>
              <% if book_comment.user == current_user %>
              <div class="comment-delete">
                <td><%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-sm btn-danger" %></td>
              </div>
              <% end %>
            </tr>
            <% end %>
          </tboby>
        </table>
      </div>

      <div class="new-comment">
        <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
          <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
          <%= f.submit "Create Book comment" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book),remote: true, method: :delete do %>
    ♥<%= book.favorites.count %>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book),remote: true, method: :post do %>
    ♡<%= book.favorites.count %>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$('#favorites_buttons_<%= @book.id %>').html("<%= j( render 'favorites/favorite', book: @book) %>");

app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @book.id %>').html("<%= j( render 'favorites/favorite', book: @book) %>");

app/views/home/about.html.erb
<h1 class="px-3 mx-auto", style="text-align: center;">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>

app/views/home/top.html.erb
<div class="top">
  <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
    <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
    <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
    <p>you can share and exchange  your opinions , inpressions , and emotions</p>
    <p> about various books!</p>
    <div class="btn-wrapper col-10 mx-auto">
      <div class="row">
        <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
      </div>
      <div class="row">
        <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_notifications.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, class: "alert alert-#{key}") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2Ver2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <h3 class="navbar-brand"><span>Bookers</span></h3>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li><a class="fas fa-home nav-link text-light" href="/users/<%= current_user.id%>"> Home</a></li>
                <li><a class="fas fa-users nav-link text-light" href="/users"> Users</a></li>
                <li><a class="fas fa-book-open nav-link text-light" href="/books"> Books</a></li>
                <li><a class="fas fa-sign-out-alt nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out"> Logout</a></li>
              <% else %>
                <li><a class="fas fa-home nav-link text-light" href="/"> Home</a></li>
                <li><a class="fas fa-link nav-link text-light" href="/home/about"> About</a></li>
                <li><a class="fas fa-user-plus nav-link text-light" href="/users/sign_up"> Sign up</a></li>
                <li><a class="fas fa-sign-in-alt nav-link text-light" href="/users/sign_in"> Login</a></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= notice %>
    <% flash.each do |message_type, message| %>
      <%= message %>
    <% end %>
    <%= yield %>
    <footer>
      <p style="text-align: center;">CopyRight Infratop.inc</p>
    </footer>
  </body>
</html>

app/views/users/_list.html.erb
 <h2>Users</h2>
    <table class='table'>
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag user, :profile_image,  size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %></td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

app/views/users/_profile.html.erb
<h2>User info</h2>
  <table class="table">
    <tr><%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></tr>
    <thead>
      <tr>
        <th>name</th>
        <th><%= @user.name %></th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th>introduction</th>
        <th><%= @user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <%= link_to edit_user_path(@user) do %>
    <i class="btn btn-outline-secondary btn-block fas fa-user-cog"></i>
  <% end %>

app/views/users/edit.html.erb
<div class="container">
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2 style="color:red"><%= pluralize(@user.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>

          <li style="color:red"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<h2>User info</h2>
<%= form_with model:@user, local:true do |f| %>
  <div class="field form-item">
    <%= f.label :Name %><br />
    <%= f.text_field :name, autofocus: true %>
  </div>
  <div class="field form-item">
    <%= f.label :Image %><br />
    <%= f.attachment_field :profile_image,  autofocus: true, placeholder: "プロフィール画像" %>
  </div>
  <div class="field form-item">
    <%= f.label :introduction %><br />
    <%= f.text_area :introduction, autofocus: true %>
  </div>
  <p><input type="submit" name="commit" value="Update User" class="btn btn-secondary" data-disable-with="Update User" /></p>
<% end %>

</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/profile' %>
      <div class="mt-3">
        <%= render 'books/form', book: @book %>
      </div>
    </div>
    <div class='col-md-8 offset-md-1'>
      <%= render 'users/list', books: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <table class="table">
        <tr><%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></tr>
        <thead>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <%= link_to edit_user_path(@user) do %>
        <i class="btn btn-outline-secondary btn-block fas fa-user-cog"></i>
      <% end %>

      <div class="mt-3">
        <%= render 'books/form', book: @book %>
      </div>
    </div>

    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <a  href="/users/<%= @user.id %>">
                  <%= attachment_image_tag @user, :profile_image,  size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %>
                </a>
               </td>
              <td><%= link_to book.title, book_path(book)  %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>